PATCH http://localhost:3001/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlM2IxOTNkNy03NjE0LTQ0YTYtYjMzZS1hNDFiZWI5YTk4OGQiLCJpYXQiOjE2OTI5NDM3NzUsImV4cCI6MTY5Mjk0NDY3NX0.NAtqp3izWXL1Q6i7QRhP-aLY-o1vBcfVle1v16T1fws