# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
    steps:
    - uses: actions/checkout@v3
    - name: "Checking NODE_ENV variables"
      run: echo "NODE_ENV is $NODE_ENV"
    - name: "Checking ACCESS_TOKEN_SECRET variables"
      run: echo "ACCESS_TOKEN_SECRET is $ACCESS_TOKEN_SECRET"
    - name: "Checking REFRESH_TOKEN_SECRET variables"
      run: echo "REFRESH_TOKEN_SECRET is $REFRESH_TOKEN_SECRET"
    - name: "Checking DATABASE_HOST variables"
      run: echo "DATABASE_HOST is $DATABASE_HOST"
    - name: "Checking DATABASE_PORT variables"
      run: echo "DATABASE_PORT is $DATABASE_PORT"
    - name: "Checking DATABASE_USER variables"
      run: echo "DATABASE_USERNAME is $DATABASE_USER"
    - name: "Checking DATABASE_PASSWORD variables"
      run: echo "DATABASE_PASSWORD is $DATABASE_PASSWORD"
    - name: "Checking DATABASE_NAME variables"
      run: echo "DATABASE_NAME is $DATABASE_NAME"
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test:e2e
